name       : libykclient
version    : 2.15
release    : 1
source     :
    - https://developers.yubico.com/yubico-c-client/Releases/ykclient-2.15.tar.gz : f461cdefe7955d58bbd09d0eb7a15b36cb3576b88adbd68008f40ea978ea5016
license    : BSD-2-Clause
component  : security.library
summary    : Yubico C client library (also known as yubico-c-client)
description: |
    YubiKey C Client Library (libykclient) is a C library used to validate an Yubikey OTP against Yubico’s servers
builddeps  :
    - pkgconfig(libcurl)
    - help2man
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
