name       : libykclient
version    : '2.15'
release    : 2
source     :
    - https://github.com/Yubico/yubico-c-client/archive/ykclient-2.15.tar.gz : 3863f4fc2f3320c59fcbf57862bba48bcb716fddb886840bb0dd8db14d5ab7f0
license    : BSD-2-Clause
component  : security.library
summary    : Yubico C client library (also known as yubico-c-client)
description: |
    YubiKey C Client Library (libykclient) is a C library used to validate an Yubikey OTP against Yubico’s servers
builddeps  :
    - pkgconfig(libcurl)
    - help2man
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
